# Utilise une image PHP 8.4
FROM php:8.4-fpm

# Installer les extensions nécessaires
RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip git curl \
 && docker-php-ext-install pdo pdo_mysql mbstring zip bcmath

# Installer composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copier le projet
WORKDIR /var/www
COPY . .

# Installer les dépendances
RUN composer install --optimize-autoloader --no-interaction

# Commande par défaut
CMD ["php-fpm"]
